<a href="https://colab.research.google.com/github/2004sreedevip/ML-Lab-/blob/main/ML_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Activity1: Create Arrays
import numpy as np
a = np.array([10,20,30,40])
print(a)

b = np.arange(1,11)
print(b)

c = np.linspace(0,1,5)
print(c)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#Activity 2:Matrix operation
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A+B)
print(A-B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
#Activity 3: min and max marks
marks = np.array([70,65,80,90,88])
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))

78.6
90
65
9.789790600416334


In [ ]:
#Activity 4: using pandas
import pandas as pd

student = {
    "Name" :["A","B","c","D"],
    "Age" :[21,22,23,24],
    "Marks" :[78,65,90,85]
}

df = pd.DataFrame(student)

df

,Name,Age,Marks
0,A,21,78
1,B,22,65
2,c,23,90
3,D,24,85


In [ ]:
#Activity 5: Reading Dataset
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)

df = iris.frame

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [ ]:
#Activity 6: Basic operations
df.info()

df.describe()

df.shape

df.columns

df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2


In [ ]:
#Activity 7:Selecting Data
df[['sepal length (cm)', 'target']]

df.iloc[:5]

df.loc[10:20]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0


In [ ]:
#Activity 8:Filtering
df[df['target']==1]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1


In [ ]:
#Activity 9: Sorting
df.sort_values(by='sepal length (cm)')

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
13,4.3,3.0,1.1,0.1,0
8,4.4,2.9,1.4,0.2,0
42,4.4,3.2,1.3,0.2,0
38,4.4,3.0,1.3,0.2,0
41,4.5,2.3,1.3,0.3,0
...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,2
117,7.7,3.8,6.7,2.2,2
118,7.7,2.6,6.9,2.3,2
135,7.7,3.0,6.1,2.3,2


In [ ]:
#Activity10:Find total no of passengers, avg age of survivers and non survivers, list the passengers who are older 60yrs, and find the avg fare for each passengers
import pandas as pd
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
total_passengers = df["PassengerId"].count()
print("Total no of passengers:", total_passengers)

Total no of passengers: 891


In [ ]:
survivors = df[df["Survived"]==1]
avg_survivor_age = survivors["Age"].mean()
print("Avg age of survivors:", avg_survivor_age)

Avg age of survivors: 28.343689655172415


In [ ]:
non_survivors = df[df["Survived"]==0]
avg_non_survivor_age = non_survivors["Age"].mean()
print("Avg age of non survivors:", avg_non_survivor_age)

Avg age of non survivors: 30.62617924528302


In [ ]:
older_60 = df[df["Age"]>60]
print("Passengers older than 60 years:")
print(older_60)

Passengers older than 60 years:
     PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis

In [ ]:
avg_fare = df["Fare"].mean()
print("Average fare:", avg_fare)

Average fare: 32.204207968574636


In [ ]:
#Activity 4: Calculating the weather data of manipal
import pandas as pd
df = pd.read_csv("weatherdata.csv", skiprows=9)

In [ ]:
print(df.head())

       timestamp  Basel Temperature [2 m elevation corrected]
0  20250101T0000                                    -1.109755
1  20250101T0100                                    -1.299755
2  20250101T0200                                    -1.529754
3  20250101T0300                                    -1.599755
4  20250101T0400                                    -1.219755


In [ ]:
print(df.columns.tolist())

['timestamp', 'Basel Temperature [2 m elevation corrected]']


In [ ]:
temp = pd.to_numeric(
    df["Basel Temperature [2 m elevation corrected]"],
    errors = "coerce"
)

In [ ]:
print("Minimum temperature:", temp.min())

Minimum temperature: -9.029755


In [ ]:
print("Maximum temperature:", temp.max())

Maximum temperature: 39.070248


In [ ]:
print("Average temperature:", temp.mean())

Average temperature: 12.362405106641267


In [ ]:
above_35 = temp[temp > 35]

print(above_35)

4334     35.290250
4335     35.570248
4380     35.090250
4381     35.250248
4382     35.520250
           ...    
13810    35.620247
13811    37.440247
13812    38.120247
13813    37.970245
13814    35.550247
Name: Basel Temperature [2 m elevation corrected], Length: 80, dtype: float64


In [ ]:
cold = temp[temp <= 35]
heat = temp[temp > 35]

print("Minimum cold:", cold.min())
print("Maximum cold:", cold.max())
print("Minimum heat:", heat.min())
print("Maximum heat:", heat.max())

Minimum cold: -9.029755
Maximum cold: 34.980247
Minimum heat: 35.030247
Maximum heat: 39.070248
